environment:
  nodejs_version: "14.x"

platform:
  - x64

install:
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:platform
  - node -v
  - npm -v
  - npm install -g yarn
  - yarn install

cache:
  - node_modules -> yarn.lock

test_script:
  - yarn test
  - yarn run mocha

build: off
